apiVersion: v1
kind: Service
metadata:
  name: default-backend-svc
  namespace: check
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: default-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: nginx:alpine
        args:
        - /bin/sh
        - -c
        - |
          echo "HTTP/1.1 404 Not Found\n\nNot Found" > /usr/share/nginx/html/404.html && nginx -g 'daemon off;'
        ports:
        - containerPort: 80