apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: logging-dev
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://loki-dev.logging-dev.svc.cluster.local:3100
      isDefault: true